language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6.gemfile
